In [1]:
import numpy as np

In [41]:
arr = np.random.randint(1,55,25)
arr

array([21, 52, 11, 44, 46, 17, 35, 52, 36, 45, 41, 41, 10, 11, 41, 54, 18,
       14, 54, 52, 29, 11, 13, 24, 54])

In [43]:
arr = arr.reshape(5,5)
arr

array([[21, 52, 11, 44, 46],
       [17, 35, 52, 36, 45],
       [41, 41, 10, 11, 41],
       [54, 18, 14, 54, 52],
       [29, 11, 13, 24, 54]])

In [47]:
arr[2:,0:2]

array([[41, 41],
       [54, 18],
       [29, 11]])

In [48]:
arr[1:4,1:4]

array([[35, 52, 36],
       [41, 10, 11],
       [18, 14, 54]])